In [1]:
#Write a program to demonstrate ART 
import numpy as np

class ART:
    def __init__(self, input_size, vigilance):
        self.input_size = input_size
        self.vigilance = vigilance
        self.weights = np.zeros((1, input_size))

    def normalize(self, x):
        return x / np.sum(x)

    def match(self, x):
        while True:
            net_input = np.dot(self.weights, x)
            net_input_norm = self.normalize(net_input)
            winner_index = np.argmax(net_input_norm)

            if net_input_norm[winner_index] >= self.vigilance:
                return winner_index
            else:
                self.weights = np.vstack([self.weights, x])
                return self.weights.shape[0] - 1

# Example usage
input_size = 5
vigilance = 0.9

art = ART(input_size, vigilance)

# Training data
data = np.array([[1, 0, 1, 0, 1],
                 [0, 1, 0, 1, 0],
                 [1, 1, 0, 1, 1]])

# Train the ART network
for pattern in data:
    winner = art.match(pattern)
    print("Pattern:", pattern)
    print("Winner:", winner)
    print("Weights:", art.weights)
    print()

# Test the ART network
test_data = np.array([[1, 0, 0, 1, 0],
                      [0, 1, 1, 0, 1]])

for pattern in test_data:
    winner = art.match(pattern)
    print("Pattern:", pattern)
    print("Winner:", winner)
    print("Weights:", art.weights)
    print()

Pattern: [1 0 1 0 1]
Winner: 1
Weights: [[0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]]

Pattern: [0 1 0 1 0]
Winner: 2
Weights: [[0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]

Pattern: [1 1 0 1 1]
Winner: 3
Weights: [[0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 1. 0. 1. 1.]]

Pattern: [1 0 0 1 0]
Winner: 4
Weights: [[0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 1. 0. 1. 1.]
 [1. 0. 0. 1. 0.]]

Pattern: [0 1 1 0 1]
Winner: 5
Weights: [[0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 1. 0. 1. 1.]
 [1. 0. 0. 1. 0.]
 [0. 1. 1. 0. 1.]]



<ipython-input-1-718170019f30>:10: RuntimeWarning: invalid value encountered in true_divide
  return x / np.sum(x)
